openapi: 3.0.3


info:
  title: FinancialReport Specification
  description: Open API specification for a financial accounting project
  version: 1.0.0


servers:
  - url: http://localhost:8080/


tags:
  - name: Authorization
    description: endpoints for authorization


paths:

  /user/api/auth/register:
    post:
      tags:
        - Authorization
      summary: create new Client
      operationId: registerNewClient
      requestBody:
        $ref: "#/components/requestBodies/NewClient"
      responses:
        201:
          $ref: "#/components/responses/Client"
        400:
          $ref: "#/components/responses/ErrorInfoList"
        500:
          $ref: "#/components/responses/ErrorInfoList"


components:
  requestBodies:
    NewClient:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NewClient"


  responses:
    Client:
      description: Client
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Client"

    ErrorInfoList:
      description: Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfoList"


  schemas:
    NewClient:
      properties:
        username:
          type: string
        password:
          type: string
          format: password
        email:
          type: string
          format: email
        firstname:
          type: string
        lastname:
          type: string
        birthday:
          type: string
          format: date
      required:
        - username
        - password
        - email

    Client:
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
          format: email
        firstname:
          type: string
        lastname:
          type: string
        birthday:
          type: string
          format: date
      required:
        - id
        - username
        - email

    ErrorInfoList:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ErrorInfo"
      required:
        - errors

    ErrorInfo:
      type: object
      properties:
        code:
          type: string
          description: A unique identifier for the error
        title:
          type: string
          description: A brief human-readable message
        detail:
          type: string
          description: A lengthier explanation of the error
      required:
        - code
        - title